name: Ubuntu 22.04 Iron Build

on:
  pull_request:
    branches:
      - iron
  push:
    branches:
      - iron
  schedule:
    # At 7:01 & 20:01 only on Sunday
    - cron:  '01 7,20 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    timeout-minutes: 20
    runs-on: self-hosted
    container:
      image: ${{ vars.LOCAL_DOCKER_REGISTRY_IP }}:5000/roxy_iron:base

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.MYORG_REPO_ACCESS_TOKEN }}
      run: |
        git config --global url."https://roncapat:${TOKEN}@github.com".insteadOf "https://github.com"
        cat ~/.gitconfig

    - name: Run Tests
      timeout-minutes: 10
      uses: ros-tooling/action-ros-ci@0.3.6
      with:
        target-ros2-distro: iron
        import-token: ${{ secrets.GITHUB_TOKEN }}
        skip-rosdep-install: true
        colcon-defaults: |
          {
            "build": {
                "merge-install": true,
                "cmake-args": [
                    "-D_FORTIFY_SOURCE=3",
                    "-D_GLIBCXX_ASSERTIONS=1",
                    "-DCMAKE_C_FLAGS=-march=native -fopenmp",
                    "-DCMAKE_CXX_FLAGS=-march=native -fopenmp"
                ]
            },
            "test": {
                "merge-install": true
            }
          }
